[package]
name = "lyra-downloads-aria2"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gettext-rs.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
reqwest.workspace = true
rand = "0.8"
libc = "0.2"
